package views;

import controllers.CtrlSettings;
import java.awt.Cursor;
import java.awt.Desktop;
import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.border.TitledBorder;

/* LICENSE
 * Creative CommonUtils Zero v1.0 Universal
 * CC0 1.0 Universal
 * Please check out the license file in this project's root folder.
 */

/** Third Party Software, Plugins and Graphical Resources Attribution Window
 * @author Clark - ClarkCodes
 * @since 1.0
 * */
public class DlgAttribution extends javax.swing.JDialog
{
    private final CtrlSettings ctrlSettings;
    private final String formDevLinkURL = "https://www.formdev.com/flatlaf/";
    private final String materialIconsLinkURL = "https://fonts.google.com/icons";
    private final String jLayerLinkURL = "https://search.maven.org/artifact/javazoom/jlayer/1.0.1/jar";
    
    public DlgAttribution ( java.awt.Frame parent, boolean modal )
    {
        super( parent, modal );
        initComponents();
        setLocationRelativeTo( null );
        ctrlSettings = CtrlSettings.getController();
        this.setIconImage( ctrlSettings.getGroupsAttributionIconForAttributionForm().getImage() );
        updateComponentsLanguage();
        
        // Linked Label for FormDev URL
        addMouseClickListenerToLabel( this.lblFormDevLink, formDevLinkURL );
        
        // Linked Label for MaterialIcons URL
        addMouseClickListenerToLabel( this.lblMaterialIconsLink, materialIconsLinkURL );
        
        // Linked Label for JLayer URL
        addMouseClickListenerToLabel( this.lblJLayerLink, jLayerLinkURL );
    }

    private void addMouseClickListenerToLabel( JLabel linkedLabel, String url )
    {
        linkedLabel.setText( "<html><a href=\"#\">" + url + "</a></html>" );
        linkedLabel.setCursor( Cursor.getPredefinedCursor( Cursor.HAND_CURSOR ) );
        linkedLabel.addMouseListener( new MouseAdapter()
        {
            @Override
            public void mouseClicked ( MouseEvent e )
            {
                try
                {
                    Desktop.getDesktop().browse( new URI( url ) );
                }
                catch ( IOException | URISyntaxException ex )
                {
                    JOptionPane.showMessageDialog( null, 
                            java.text.MessageFormat.format( 
                                    CtrlSettings.getLanguageBundle().getString( "key_attrib_link_opening _error_msg" ), 
                                    new Object[]
                                    {
                                        url
                                    } ), 
                            CtrlSettings.getLanguageBundle().getString( "key_attribution" ), 
                            JOptionPane.WARNING_MESSAGE );
                }
            }

        } );
    }
    
    private void updateComponentsLanguage()
    {
        this.setTitle( CtrlSettings.getLanguageBundle().getString( "key_attribution" ) );
        
        panelLafTitle.setBorder( BorderFactory.createTitledBorder( 
            null, CtrlSettings.getLanguageBundle().getString( "key_attrib_laf_title" ), 
            TitledBorder.DEFAULT_JUSTIFICATION, 
            TitledBorder.DEFAULT_POSITION, 
            new Font( "Segoe UI", 1, 16 ) ) );
         
        panelIconsTitle.setBorder( BorderFactory.createTitledBorder( 
            null, CtrlSettings.getLanguageBundle().getString( "key_attrib_used_icons" ), 
            TitledBorder.DEFAULT_JUSTIFICATION, 
            TitledBorder.DEFAULT_POSITION, 
            new Font( "Segoe UI", 1, 16 ) ) );
        
        panelSoundsTitle.setBorder( BorderFactory.createTitledBorder( 
            null, CtrlSettings.getLanguageBundle().getString( "key_attrib_mp3_audio_title" ), 
            TitledBorder.DEFAULT_JUSTIFICATION, 
            TitledBorder.DEFAULT_POSITION, 
            new Font( "Segoe UI", 1, 16 ) ) );
         
        lblResourcesIn1.setText( CtrlSettings.getLanguageBundle().getString( "key_attrib_resources_found_on" ) );
        lblResourcesIn2.setText( CtrlSettings.getLanguageBundle().getString( "key_attrib_resources_found_on" ) );
        lblResourcesIn3.setText( CtrlSettings.getLanguageBundle().getString( "key_attrib_resources_found_on" ) );
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        panelLafTitle = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        lblResourcesIn1 = new javax.swing.JLabel();
        lblFormDevLink = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        panelIconsTitle = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        lblResourcesIn2 = new javax.swing.JLabel();
        lblMaterialIconsLink = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        panelSoundsTitle = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        lblResourcesIn3 = new javax.swing.JLabel();
        lblJLayerLink = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("i18n/i18nBundle_es"); // NOI18N
        panelLafTitle.setBorder(javax.swing.BorderFactory.createTitledBorder(null, bundle.getString("key_attrib_laf_title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 16))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel11.setText("Flat Look And Feel: FlatLaf 3.1.1");

        lblResourcesIn1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblResourcesIn1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResourcesIn1.setText(bundle.getString("key_attrib_resources_found_on")); // NOI18N

        lblFormDevLink.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblFormDevLink.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFormDevLink.setText("FormDev Link"); // NOI18N

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel12.setText("FormDev Software:");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel14.setText("FlatLaf IntelliJ Themes 3.1.1");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel15.setText("FlatLaf Extras 3.1.1");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel18.setText("SVG Salamander 1.1.4");

        javax.swing.GroupLayout panelLafTitleLayout = new javax.swing.GroupLayout(panelLafTitle);
        panelLafTitle.setLayout(panelLafTitleLayout);
        panelLafTitleLayout.setHorizontalGroup(
            panelLafTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLafTitleLayout.createSequentialGroup()
                .addGroup(panelLafTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLafTitleLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelLafTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblResourcesIn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblFormDevLink, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panelLafTitleLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(panelLafTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelLafTitleLayout.setVerticalGroup(
            panelLafTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLafTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblResourcesIn1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFormDevLink, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelIconsTitle.setBorder(javax.swing.BorderFactory.createTitledBorder(null, bundle.getString("key_attrib_used_icons"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 16))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel13.setText("Material Icons");

        lblResourcesIn2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblResourcesIn2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResourcesIn2.setText(bundle.getString("key_attrib_resources_found_on")); // NOI18N

        lblMaterialIconsLink.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblMaterialIconsLink.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMaterialIconsLink.setText("Material Icons Link"); // NOI18N

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel19.setText("Google Fonts:");

        javax.swing.GroupLayout panelIconsTitleLayout = new javax.swing.GroupLayout(panelIconsTitle);
        panelIconsTitle.setLayout(panelIconsTitleLayout);
        panelIconsTitleLayout.setHorizontalGroup(
            panelIconsTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIconsTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelIconsTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblResourcesIn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMaterialIconsLink, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelIconsTitleLayout.createSequentialGroup()
                        .addGroup(panelIconsTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelIconsTitleLayout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 303, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelIconsTitleLayout.setVerticalGroup(
            panelIconsTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIconsTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblResourcesIn2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMaterialIconsLink, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelSoundsTitle.setBorder(javax.swing.BorderFactory.createTitledBorder(null, bundle.getString("key_attrib_mp3_audio_title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 16))); // NOI18N

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel16.setText("JLayer 1.0.1");

        lblResourcesIn3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblResourcesIn3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResourcesIn3.setText(bundle.getString("key_attrib_resources_found_on")); // NOI18N

        lblJLayerLink.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblJLayerLink.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJLayerLink.setText("JLayer Link"); // NOI18N

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel20.setText("JavaZoom:");

        javax.swing.GroupLayout panelSoundsTitleLayout = new javax.swing.GroupLayout(panelSoundsTitle);
        panelSoundsTitle.setLayout(panelSoundsTitleLayout);
        panelSoundsTitleLayout.setHorizontalGroup(
            panelSoundsTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSoundsTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSoundsTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblResourcesIn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblJLayerLink, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelSoundsTitleLayout.createSequentialGroup()
                        .addGroup(panelSoundsTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelSoundsTitleLayout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 303, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelSoundsTitleLayout.setVerticalGroup(
            panelSoundsTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSoundsTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblResourcesIn3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblJLayerLink, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panelSoundsTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelIconsTitle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelLafTitle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(panelLafTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelIconsTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelSoundsTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 718, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFormDevLink;
    private javax.swing.JLabel lblJLayerLink;
    private javax.swing.JLabel lblMaterialIconsLink;
    private javax.swing.JLabel lblResourcesIn1;
    private javax.swing.JLabel lblResourcesIn2;
    private javax.swing.JLabel lblResourcesIn3;
    private javax.swing.JPanel panelIconsTitle;
    private javax.swing.JPanel panelLafTitle;
    private javax.swing.JPanel panelSoundsTitle;
    // End of variables declaration//GEN-END:variables
}
