package views;

import controllers.CommonUtils;
import controllers.CtrlSettings;
import controllers.CtrlSmallvilleClock;

/** Stopwatch Laps {@code JDialog} window
 * @author Clark - ClarkCodes
 * @since 1.0
 */
public class DlgStopwatchLaps extends javax.swing.JDialog
{
    CtrlSmallvilleClock clocksManager;
    CtrlSettings ctrlSettings;
    /** Creates new form DlgStopwatchLaps */
    public DlgStopwatchLaps ( java.awt.Frame parent, boolean modal )
    {
        super( parent, modal );
        initComponents();
        clocksManager = CtrlSmallvilleClock.getController();
        ctrlSettings = CtrlSettings.getController();
        tableLapsModelSetter();
        
        setLocation( Math.toIntExact( Math.round( parent.getLocationOnScreen().getX() ) ), Math.toIntExact( Math.round( parent.getLocationOnScreen().getY() + parent.getHeight() ) ) );
        
//        if ( CtrlSettings.getAppMode() == CtrlSettings.Mode.EXPANDED )
//        {
//            setLocation( Math.toIntExact( Math.round( parent.getLocationOnScreen().getX() ) ), Math.toIntExact( Math.round( parent.getLocationOnScreen().getY() + parent.getHeight() ) ) );
//        }
//        else
//        {
//            JFrame miniWindow = CommonUtils.getMiniWindow();
//            setLocation( Math.toIntExact( Math.round( miniWindow.getLocationOnScreen().getX() ) ), Math.toIntExact( Math.round( miniWindow.getLocationOnScreen().getY() + miniWindow.getHeight() ) ) );
//        }
        
        setTitle( CtrlSettings.getLanguageBundle().getString( "key_marked_laps" ) );
                
        // Call to fill Laps Table
        if ( !clocksManager.getStopwatchLaps().isEmpty() )
            clocksManager.fillStopwatchLapsTable( tblLaps );
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblLaps = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        mnuOpen = new javax.swing.JMenuItem();
        mnuSaveAs = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });

        tblLaps.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tblLaps.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {

            }
        ));
        tblLaps.setRowHeight(40);
        jScrollPane1.setViewportView(tblLaps);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("i18n/i18nBundle_es"); // NOI18N
        menuFile.setText(bundle.getString("key_file")); // NOI18N

        mnuOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuOpen.setText(bundle.getString("key_open")); // NOI18N
        mnuOpen.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                mnuOpenActionPerformed(evt);
            }
        });
        menuFile.add(mnuOpen);

        mnuSaveAs.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuSaveAs.setText(bundle.getString("key_save_as")); // NOI18N
        mnuSaveAs.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                mnuSaveAsActionPerformed(evt);
            }
        });
        menuFile.add(mnuSaveAs);

        jMenuBar1.add(menuFile);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuOpenActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mnuOpenActionPerformed
    {//GEN-HEADEREND:event_mnuOpenActionPerformed
        clocksManager.openStopwatchLaps();
        updateLapsTable();
    }//GEN-LAST:event_mnuOpenActionPerformed

    private void mnuSaveAsActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mnuSaveAsActionPerformed
    {//GEN-HEADEREND:event_mnuSaveAsActionPerformed
        if ( !clocksManager.getStopwatchLaps().isEmpty() )
            clocksManager.saveStopwatchLaps();
    }//GEN-LAST:event_mnuSaveAsActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        // Setting Menus Icons
        this.mnuOpen.setIcon( ctrlSettings.getSourceOpenIcon() );
        this.mnuSaveAs.setIcon( ctrlSettings.getSaveIcon() );
        updateComponentsLanguage();
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
    {//GEN-HEADEREND:event_formWindowClosing
        if ( clocksManager.getStopwatch().getState() == CommonUtils.State.STOPPED )
            clocksManager.getStopwatchLaps().clear();
    }//GEN-LAST:event_formWindowClosing
    /** Sets the {@code DefaultTableModel} of the laps table
     */
    private void tableLapsModelSetter()
    {
        tblLaps.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "N°", 
                CtrlSettings.getLanguageBundle().getString( "key_global_time" ), 
                CtrlSettings.getLanguageBundle().getString( "key_lap_time" )
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean []
            {
                false, false, false
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
    }
    /** Updates laps table information from the Stopwatch Laps collection
     */
    public void updateLapsTable()
    {
        if ( !clocksManager.getStopwatchLaps().isEmpty() )
        {
            clocksManager.fillStopwatchLapsTable( tblLaps );
        }
        else
        {
            CommonUtils.clearTable( tblLaps );
        }
    }
    /** Updates menus components language
     */
    private void updateComponentsLanguage()
    {
        menuFile.setText( CtrlSettings.getLanguageBundle().getString( "key_file" ) );
        mnuOpen.setText( CtrlSettings.getLanguageBundle().getString( "key_open" ) );
        mnuSaveAs.setText( CtrlSettings.getLanguageBundle().getString( "key_save_as" ) );
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenuItem mnuOpen;
    private javax.swing.JMenuItem mnuSaveAs;
    private javax.swing.JTable tblLaps;
    // End of variables declaration//GEN-END:variables
}
