package views;

import controllers.CtrlSettings;
import controllers.CtrlSmallvilleClock;
import javax.swing.JLabel;

/** Big System World Clock {@code JPanel}
 * @author Clark - ClarkCodes
 * @since 1.0
 */
public class IfrmBigClock extends javax.swing.JPanel
{
    CtrlSmallvilleClock clocksManager;
    /** Creates new form IfrmShortClocks */
    public IfrmBigClock ()
    {
        initComponents();
        clocksManager = CtrlSmallvilleClock.getController();
        btnAddWorldClock.setIcon( CtrlSettings.getController().getAddTimerIcon() );
        btnAddWorldClock.setToolTipText( CtrlSettings.getLanguageBundle().getString( "key_add_world_clock" ) );
    }

    public JLabel getLblDate ()
    {
        return lblDate;
    }

    public JLabel getLblWorldClock ()
    {
        return lblWorldClock;
    }

    public JLabel getLblZone ()
    {
        return lblZone;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        lblWorldClock = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblZone = new javax.swing.JLabel();
        btnAddWorldClock = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(500, 236));
        setMinimumSize(new java.awt.Dimension(500, 236));
        setPreferredSize(new java.awt.Dimension(500, 236));
        setLayout(null);

        lblWorldClock.setFont(new java.awt.Font("Exo", 0, 72)); // NOI18N
        lblWorldClock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWorldClock.setText("00:00");
        add(lblWorldClock);
        lblWorldClock.setBounds(-4, -4, 500, 200);

        lblDate.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDate.setText(" ");
        add(lblDate);
        lblDate.setBounds(0, 140, 500, 22);

        lblZone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblZone.setText(" ");
        add(lblZone);
        lblZone.setBounds(0, 170, 500, 16);

        btnAddWorldClock.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("i18n/i18nBundle_es"); // NOI18N
        btnAddWorldClock.setToolTipText(bundle.getString("key_add_world_clock")); // NOI18N
        btnAddWorldClock.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAddWorldClockActionPerformed(evt);
            }
        });
        add(btnAddWorldClock);
        btnAddWorldClock.setBounds(442, 184, 48, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddWorldClockActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAddWorldClockActionPerformed
    {//GEN-HEADEREND:event_btnAddWorldClockActionPerformed
        DlgZoneIdSelector zoneSelector = new DlgZoneIdSelector( null, true );
        zoneSelector.setVisible( true );
    }//GEN-LAST:event_btnAddWorldClockActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddWorldClock;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblWorldClock;
    private javax.swing.JLabel lblZone;
    // End of variables declaration//GEN-END:variables
}
