package views;

import javax.swing.JLabel;

/**
 *
 * @author Administrador
 */
public class IfrmShortClock extends javax.swing.JPanel
{

    /** Creates new form IfrmShortClocks */
    public IfrmShortClock ()
    {
        initComponents();
    }

    public JLabel getLblDate ()
    {
        return lblDate;
    }

    public JLabel getLblWorldClock ()
    {
        return lblWorldClock;
    }

    public JLabel getLblZone ()
    {
        return lblZone;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        lblWorldClock = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblZone = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(165, 116));
        setMinimumSize(new java.awt.Dimension(165, 116));
        setPreferredSize(new java.awt.Dimension(165, 116));
        setLayout(null);

        lblWorldClock.setFont(new java.awt.Font("Exo", 0, 48)); // NOI18N
        lblWorldClock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWorldClock.setText("00:00");
        add(lblWorldClock);
        lblWorldClock.setBounds(0, 0, 165, 90);

        lblDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDate.setText(" ");
        add(lblDate);
        lblDate.setBounds(0, 70, 165, 16);

        lblZone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblZone.setText(" ");
        add(lblZone);
        lblZone.setBounds(0, 90, 165, 16);
    }// </editor-fold>//GEN-END:initComponents


    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblWorldClock;
    private javax.swing.JLabel lblZone;
    // End of variables declaration//GEN-END:variables
}
